package tools

import (
	"bytes"
	"context"
	"os"
	"path/filepath"
	"testing"

	"github.com/MattCheramie/GopherTrunk/internal/cryptolab"
)

func writeFile(t *testing.T, name string, data []byte) string {
	t.Helper()
	p := filepath.Join(t.TempDir(), name)
	if err := os.WriteFile(p, data, 0o644); err != nil {
		t.Fatal(err)
	}
	return p
}

func runMode(t *testing.T, toolName, modeName string, args []string) *cryptolab.Result {
	t.Helper()
	_, mode, err := cryptolab.LookupMode(toolName, modeName)
	if err != nil {
		t.Fatalf("lookup %s/%s: %v", toolName, modeName, err)
	}
	env := cryptolab.Env{Stdout: &bytes.Buffer{}, Format: cryptolab.FormatText}
	res, err := mode.Run(context.Background(), args, env)
	if err != nil {
		t.Fatalf("%s/%s run: %v", toolName, modeName, err)
	}
	return res
}

func TestAllGenericToolsRegistered(t *testing.T) {
	t.Parallel()
	for _, name := range []string{"stats", "brute", "lfsr", "crc", "descramble"} {
		if _, ok := cryptolab.Lookup(name); !ok {
			t.Fatalf("tool %q not registered", name)
		}
	}
}

func TestStatsScan(t *testing.T) {
	t.Parallel()
	in := writeFile(t, "p.bin", []byte("the quick brown fox jumps over the lazy dog again and again"))
	res := runMode(t, "stats", "scan", []string{"-in", in})
	if res.Tool != "stats" || len(res.Fields) == 0 {
		t.Fatalf("unexpected result %+v", res)
	}
}

func TestBruteXORRecovers(t *testing.T) {
	t.Parallel()
	pt := []byte("CALL UNIT 12 ON CHANNEL 7 FOR THE DISPATCH BRIDGE NOW PLEASE OK")
	ct := make([]byte, len(pt))
	for i := range pt {
		ct[i] = pt[i] ^ 0x6B
	}
	in := writeFile(t, "c.bin", ct)
	res := runMode(t, "brute", "xor", []string{"-in", in})
	if len(res.Findings) == 0 {
		t.Fatal("no findings")
	}
}

func TestCRCRecoverTool(t *testing.T) {
	t.Parallel()
	// Build frames.txt (datahex,crchex) with CRC-16/GSM computed by a local
	// helper, so the expected values aren't produced by the code under test.
	lines := ""
	for _, d := range []string{"52414449", "554e49542d3037", "44495350"} {
		data := mustHex(t, d)
		c := crc16gsm(data)
		lines += d + "," + itoaHex(c) + "\n"
	}
	in := writeFile(t, "frames.txt", []byte(lines))
	res := runMode(t, "crc", "recover", []string{"-in", in, "-widths", "16"})
	if len(res.Findings) == 0 {
		t.Fatalf("no CRC candidates recovered: %+v", res)
	}
}

func TestLFSRBMTool(t *testing.T) {
	t.Parallel()
	// A few bytes of a structured sequence; just confirm the tool runs and
	// reports a complexity field.
	in := writeFile(t, "ks.bin", []byte{0x01, 0x23, 0x45, 0x67, 0x89, 0xab})
	res := runMode(t, "lfsr", "bm", []string{"-in", in})
	if len(res.Fields) == 0 {
		t.Fatalf("no fields: %+v", res)
	}
}

func TestDescrambleInvertRoundTrip(t *testing.T) {
	t.Parallel()
	pcm := []byte{0x10, 0x00, 0x20, 0x00, 0x30, 0x00, 0x40, 0x00}
	in := writeFile(t, "s.s16", pcm)
	outDir := t.TempDir()
	out1 := filepath.Join(outDir, "i1.s16")
	runMode(t, "descramble", "invert", []string{"-in", in, "-out", out1})
	out2 := filepath.Join(outDir, "i2.s16")
	runMode(t, "descramble", "invert", []string{"-in", out1, "-out", out2})
	got, err := os.ReadFile(out2)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(got, pcm) {
		t.Fatalf("double invert != original: %v vs %v", got, pcm)
	}
}

// --- tiny local CRC-16/GSM + hex helpers, independent of the engine, so the
// test's expected values aren't generated by the code under test. ---

func crc16gsm(data []byte) uint64 {
	crc := uint16(0)
	for _, b := range data {
		crc ^= uint16(b) << 8
		for i := 0; i < 8; i++ {
			if crc&0x8000 != 0 {
				crc = (crc << 1) ^ 0x1021
			} else {
				crc <<= 1
			}
		}
	}
	return uint64(crc ^ 0xFFFF)
}

func mustHex(t *testing.T, s string) []byte {
	t.Helper()
	b := make([]byte, len(s)/2)
	for i := 0; i < len(b); i++ {
		var v int
		_, err := fscan(s[2*i:2*i+2], &v)
		if err != nil {
			t.Fatal(err)
		}
		b[i] = byte(v)
	}
	return b
}

func fscan(s string, v *int) (int, error) {
	n := 0
	for _, c := range s {
		n *= 16
		switch {
		case c >= '0' && c <= '9':
			n += int(c - '0')
		case c >= 'a' && c <= 'f':
			n += int(c-'a') + 10
		case c >= 'A' && c <= 'F':
			n += int(c-'A') + 10
		}
	}
	*v = n
	return 1, nil
}

func itoaHex(v uint64) string {
	const digits = "0123456789abcdef"
	if v == 0 {
		return "0"
	}
	var buf []byte
	for v > 0 {
		buf = append([]byte{digits[v&0xf]}, buf...)
		v >>= 4
	}
	return string(buf)
}
