package framing

// TETRA scrambling sequence per ETSI EN 300 392-2 §8.2.5.
//
// Scrambling transforms K4 type-4 bits into K5 = K4 type-5 bits via
// XOR with a deterministic pseudo-random sequence p(k) generated by
// a 32-tap linear feedback shift register seeded with the 30-bit
// extended colour code.
//
// Connection polynomial (§8.2.5.2 eq. 8.40):
//
//	c(x) = 1 + X + X^2 + X^4 + X^5 + X^7 + X^8 + X^10 + X^11
//	     + X^12 + X^16 + X^22 + X^23 + X^26 + X^32
//
// The recurrence is p(k) = sum_{i=1..32} c_i * p(k-i) (§8.2.5.2
// eq. 8.41) with initialisation p(-31) = p(-30) = 1, p(-29) =
// e(30), p(-28) = e(29), ..., p(0) = e(1) per §8.2.5.2 eq. 8.42.
// For BSCH and BSCH-Q the colour-code bits e(1)..e(30) are all
// zero (§8.2.5.2, second paragraph).
//
// Output bits are generated starting at p(1).

// scrambleTetraTapMask encodes the connection polynomial as a
// uint32 bit pattern: bit (i-1) is set iff c_i = 1 for i in 1..32.
// Taps at i = 1, 2, 4, 5, 7, 8, 10, 11, 12, 16, 22, 23, 26, 32 →
// bit positions 0, 1, 3, 4, 6, 7, 9, 10, 11, 15, 21, 22, 25, 31.
const scrambleTetraTapMask uint32 = 0x82608EDB

// ScramblerTetra produces the TETRA scrambling sequence one bit at
// a time. Construct via NewScramblerTetra. Calling Next() returns
// p(1), p(2), p(3), ... in order. Reuse the helper for both
// scrambling (encode side) and descrambling (decode side) since
// the operation is XOR-symmetric.
type ScramblerTetra struct {
	// state holds the 32 most recent p(k) values, oldest in the
	// high bits, newest in the low bits. After initialisation
	// state bit i (i = 0..29) = e(i+1); state bit 30 = state bit
	// 31 = 1 (the constant p(-30) = p(-31) = 1).
	state uint32
}

// NewScramblerTetra constructs a fresh scrambler seeded by the
// 30-bit extended colour code. The low 30 bits of colourCode hold
// e(1)..e(30) with bit i = e(i+1). Pass 0 for BSCH / BSCH-Q.
func NewScramblerTetra(colourCode uint32) *ScramblerTetra {
	return &ScramblerTetra{
		state: (colourCode & 0x3FFFFFFF) | 0xC0000000,
	}
}

// Next advances the LFSR by one step and returns the next bit
// p(k) of the scrambling sequence (0 or 1).
func (s *ScramblerTetra) Next() byte {
	// New bit = XOR of tapped state bits.
	v := s.state & scrambleTetraTapMask
	bit := byte(popcount32(v) & 1)
	// Shift state right, inserting the new bit at the top.
	s.state = (s.state >> 1) | (uint32(bit) << 31)
	return bit
}

// Generate produces the first n bits of the scrambling sequence
// p(1), p(2), ..., p(n).
func (s *ScramblerTetra) Generate(n int) []byte {
	out := make([]byte, n)
	for i := 0; i < n; i++ {
		out[i] = s.Next()
	}
	return out
}

// ScrambleTetra XORs each bit of in with the scrambling sequence
// seeded by colourCode. Returns a new slice of the same length.
// Calling this twice with the same colourCode is the identity.
func ScrambleTetra(in []byte, colourCode uint32) []byte {
	s := NewScramblerTetra(colourCode)
	out := make([]byte, len(in))
	for i, b := range in {
		out[i] = (b & 1) ^ s.Next()
	}
	return out
}

// DescrambleTetra is the inverse of ScrambleTetra. Since XOR with
// the same sequence is symmetric, the implementation is identical
// — this alias exists for call-site readability at the protocol
// layer.
func DescrambleTetra(in []byte, colourCode uint32) []byte {
	return ScrambleTetra(in, colourCode)
}

func popcount32(v uint32) int {
	v = v - ((v >> 1) & 0x55555555)
	v = (v & 0x33333333) + ((v >> 2) & 0x33333333)
	v = (v + (v >> 4)) & 0x0F0F0F0F
	return int((v * 0x01010101) >> 24)
}
