title: GopherTrunk
description: Pure-Go digital trunking radio scanner engine
url: https://gophertrunk.org
markdown: kramdown

plugins:
  - jekyll-relative-links
  - jekyll-seo-tag

relative_links:
  enabled: true
  collections: true

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: page

include:
  - README.md

exclude:
  - specs/
  - Gemfile
  - Gemfile.lock
  - vendor/
