-- GopherTrunk — initial schema migration.
--
-- Generated by consolidating the previously documentation-only schema files
-- under docs/supabase/*.sql into a single ordered migration, so the database is
-- now managed as code via the Supabase CLI (`supabase db push` / `db reset`).
--
-- Ordering follows the phase dependencies declared in each source file:
--   1. schema.sql                 (Phase 1: profiles, learn_progress, account delete)
--   2. schema-forum.sql           (Phase 2: forum tables — needs profiles)
--   3. schema-forum-moderation.sql(Phase 3: admins, reports, rate limits — needs forum)
--   4. schema-profiles.sql        (Phase 4: richer profile columns + avatar storage)
--   5. schema-moderation.sql      (Phase 5: bans, report workflow, audit — needs 2 & 3)
--
-- Every statement is idempotent (create ... if not exists / drop policy if
-- exists / guarded constraints), matching the originals, so re-applying is safe.
--
-- NOTE: the `avatars` Storage bucket referenced in section 4 must still be
-- created out-of-band (dashboard or Storage API) — a migration cannot create a
-- bucket. See the comments in that section for the required name and limits.


-- ===========================================================================
-- BEGIN schema.sql
-- ===========================================================================

-- GopherTrunk — Supabase schema (Phase 1: accounts + learning-path progress)
--
-- Apply in your Supabase project: SQL Editor -> paste -> Run (or `supabase db
-- push`). This file is committed as documentation / version history; the site
-- itself does NOT apply it. Re-running is safe — every statement is idempotent.
--
-- Security model: the site ships the PUBLIC anon key, so every table has Row
-- Level Security ENABLED with explicit policies. RLS — not key secrecy — is what
-- protects user data. Never expose the service_role key to the browser.
--
-- Forum tables (forum_categories / forum_threads / forum_posts) arrive in
-- Phase 2 as docs/supabase/schema-forum.sql.

-- ---------------------------------------------------------------------------
-- profiles — one row per auth user, auto-created on signup.
-- ---------------------------------------------------------------------------
create table if not exists public.profiles (
  id           uuid primary key references auth.users (id) on delete cascade,
  username     text unique,
  display_name text,
  avatar_url   text,
  created_at   timestamptz not null default now()
);

alter table public.profiles enable row level security;

drop policy if exists "profiles are public" on public.profiles;
create policy "profiles are public"
  on public.profiles for select using (true);

drop policy if exists "insert own profile" on public.profiles;
create policy "insert own profile"
  on public.profiles for insert with check (auth.uid() = id);

drop policy if exists "update own profile" on public.profiles;
create policy "update own profile"
  on public.profiles for update using (auth.uid() = id) with check (auth.uid() = id);

-- Auto-create a profile when a new auth user appears, seeding fields from OAuth
-- metadata (GitHub/Google) where present.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, username, display_name, avatar_url)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'user_name',
             new.raw_user_meta_data->>'preferred_username'),
    coalesce(new.raw_user_meta_data->>'name',
             new.raw_user_meta_data->>'full_name'),
    new.raw_user_meta_data->>'avatar_url'
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ---------------------------------------------------------------------------
-- learn_progress — one row per completed lesson, private to the user.
-- Matches the client store: key is (user_id, path_id, slug). `path_id` holds a
-- learning-MODULE id (e.g. "rf-sdr"). The site's "learning paths" are an optional
-- guidance layer with no rows of their own — path progress is derived from the
-- referenced modules' completions. Module ids are append-only, so these rows
-- stay valid across learning-content restructures.
-- ---------------------------------------------------------------------------
create table if not exists public.learn_progress (
  user_id      uuid not null references auth.users (id) on delete cascade,
  path_id      text not null,  -- learning-module id (append-only); not a "learning path"
  slug         text not null,
  completed_at timestamptz not null default now(),
  primary key (user_id, path_id, slug)
);

alter table public.learn_progress enable row level security;

drop policy if exists "own progress" on public.learn_progress;
create policy "own progress"
  on public.learn_progress for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- ---------------------------------------------------------------------------
-- delete_own_account() — a signed-in user deletes their own account. The
-- on-delete cascade removes their profile + progress (and, in Phase 2, their
-- forum rows). SECURITY DEFINER so it may touch auth.users; it only ever
-- deletes the caller (auth.uid()), never anyone else.
-- ---------------------------------------------------------------------------
create or replace function public.delete_own_account()
returns void
language plpgsql
security definer set search_path = public, auth
as $$
begin
  if auth.uid() is null then
    raise exception 'not authenticated';
  end if;
  delete from auth.users where id = auth.uid();
end;
$$;

revoke all on function public.delete_own_account() from public, anon;
grant execute on function public.delete_own_account() to authenticated;

-- --- END schema.sql ---

-- ===========================================================================
-- BEGIN schema-forum.sql
-- ===========================================================================

-- GopherTrunk — Supabase schema (Phase 2: forum)
--
-- Apply AFTER schema.sql, in the SQL Editor (or `supabase db push`). Idempotent.
-- Same security model as Phase 1: RLS on every table; the browser holds only the
-- public key. Forum is world-readable, posting is authenticated-only, and a user
-- can only edit/delete their own rows.
--
-- author_id references public.profiles(id) (not auth.users) so PostgREST can embed
-- the author on reads (author:profiles(...)). profiles.id === auth.users.id, so
-- `author_id = auth.uid()` in the policies still means "the signed-in user".

create extension if not exists pgcrypto;   -- gen_random_uuid()

-- ---------------------------------------------------------------------------
-- Tables
-- ---------------------------------------------------------------------------
create table if not exists public.forum_categories (
  id          uuid primary key default gen_random_uuid(),
  slug        text unique not null,
  title       text not null,
  description text,
  sort_order  int  not null default 0,
  created_at  timestamptz not null default now()
);

create table if not exists public.forum_threads (
  id          uuid primary key default gen_random_uuid(),
  category_id uuid not null references public.forum_categories(id) on delete cascade,
  author_id   uuid not null references public.profiles(id)         on delete cascade,
  title       text not null check (char_length(title) between 3 and 200),
  is_locked   boolean not null default false,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
create index if not exists forum_threads_category_idx on public.forum_threads (category_id, updated_at desc);

create table if not exists public.forum_posts (
  id         uuid primary key default gen_random_uuid(),
  thread_id  uuid not null references public.forum_threads(id) on delete cascade,
  author_id  uuid not null references public.profiles(id)      on delete cascade,
  body       text not null check (char_length(body) between 1 and 10000),
  is_deleted boolean not null default false,
  created_at timestamptz not null default now(),
  edited_at  timestamptz
);
create index if not exists forum_posts_thread_idx on public.forum_posts (thread_id, created_at);

-- ---------------------------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------------------------
alter table public.forum_categories enable row level security;
alter table public.forum_threads    enable row level security;
alter table public.forum_posts      enable row level security;

-- Categories: world-readable; writes only via the dashboard / service role
-- (no anon or authenticated write policy exists, so RLS denies them).
drop policy if exists "categories readable" on public.forum_categories;
create policy "categories readable" on public.forum_categories
  for select using (true);

-- Threads: world-readable; a signed-in user creates threads as themselves and
-- edits/deletes only their own.
drop policy if exists "threads readable" on public.forum_threads;
create policy "threads readable" on public.forum_threads
  for select using (true);

drop policy if exists "threads insert own" on public.forum_threads;
create policy "threads insert own" on public.forum_threads
  for insert to authenticated with check (author_id = auth.uid());

drop policy if exists "threads update own" on public.forum_threads;
create policy "threads update own" on public.forum_threads
  for update to authenticated using (author_id = auth.uid()) with check (author_id = auth.uid());

drop policy if exists "threads delete own" on public.forum_threads;
create policy "threads delete own" on public.forum_threads
  for delete to authenticated using (author_id = auth.uid());

-- Posts: world-readable; a signed-in user posts as themselves on an UNLOCKED
-- thread, and edits/deletes only their own (delete is soft, via is_deleted).
drop policy if exists "posts readable" on public.forum_posts;
create policy "posts readable" on public.forum_posts
  for select using (true);

drop policy if exists "posts insert own" on public.forum_posts;
create policy "posts insert own" on public.forum_posts
  for insert to authenticated with check (
    author_id = auth.uid()
    and not exists (
      select 1 from public.forum_threads t where t.id = thread_id and t.is_locked
    )
  );

drop policy if exists "posts update own" on public.forum_posts;
create policy "posts update own" on public.forum_posts
  for update to authenticated using (author_id = auth.uid()) with check (author_id = auth.uid());

drop policy if exists "posts delete own" on public.forum_posts;
create policy "posts delete own" on public.forum_posts
  for delete to authenticated using (author_id = auth.uid());

-- ---------------------------------------------------------------------------
-- Keep thread.updated_at fresh when a reply lands (drives "recent" ordering).
-- ---------------------------------------------------------------------------
create or replace function public.touch_thread_on_post()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  update public.forum_threads set updated_at = now() where id = new.thread_id;
  return new;
end;
$$;

drop trigger if exists on_forum_post_insert on public.forum_posts;
create trigger on_forum_post_insert
  after insert on public.forum_posts
  for each row execute function public.touch_thread_on_post();

-- ---------------------------------------------------------------------------
-- Starter categories — edit freely.
-- ---------------------------------------------------------------------------
insert into public.forum_categories (slug, title, description, sort_order) values
  ('general',  'General',           'Anything GopherTrunk.',                  1),
  ('help',     'Help & Support',    'Setup, tuning, and decoding questions.', 2),
  ('systems',  'Systems & Signals', 'Share systems, talkgroups, and finds.',  3),
  ('dev',      'Development',        'Building, contributing, and the code.',  4)
on conflict (slug) do nothing;

-- --- END schema-forum.sql ---

-- ===========================================================================
-- BEGIN schema-forum-moderation.sql
-- ===========================================================================

-- GopherTrunk — Supabase schema (Phase 3: forum moderation + rate limiting)
--
-- Apply AFTER schema-forum.sql, in the SQL Editor. Idempotent. Everything here
-- is additive and degrades gracefully: the client feature-detects each piece, so
-- the forum keeps working even before this file is applied.

create extension if not exists pgcrypto;

-- ---------------------------------------------------------------------------
-- Admins. Grant with:  insert into public.app_admins (user_id) values ('<uuid>');
-- (find the uuid under Authentication -> Users, or `select id from profiles`).
-- ---------------------------------------------------------------------------
create table if not exists public.app_admins (
  user_id    uuid primary key references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now()
);
alter table public.app_admins enable row level security;

-- A signed-in user may read only their own admin row (so the client can tell
-- whether to show moderation controls). No client writes — grant via SQL.
drop policy if exists "see own admin row" on public.app_admins;
create policy "see own admin row" on public.app_admins
  for select to authenticated using (user_id = auth.uid());

create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.app_admins where user_id = auth.uid());
$$;
grant execute on function public.is_admin() to authenticated, anon;

-- Admin override: admins may update/delete ANY thread or post. RLS combines
-- policies with OR, so these sit alongside the owner policies from schema-forum.
drop policy if exists "admins manage threads" on public.forum_threads;
create policy "admins manage threads" on public.forum_threads
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "admins manage posts" on public.forum_posts;
create policy "admins manage posts" on public.forum_posts
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- ---------------------------------------------------------------------------
-- Reports. Anyone signed in can file one; only admins can read them (review in
-- the dashboard, or build an admin view later).
-- ---------------------------------------------------------------------------
create table if not exists public.forum_reports (
  id          uuid primary key default gen_random_uuid(),
  post_id     uuid references public.forum_posts(id) on delete cascade,
  reporter_id uuid not null references public.profiles(id) on delete cascade,
  reason      text check (char_length(reason) <= 500),
  created_at  timestamptz not null default now()
);
alter table public.forum_reports enable row level security;

drop policy if exists "report as self" on public.forum_reports;
create policy "report as self" on public.forum_reports
  for insert to authenticated with check (reporter_id = auth.uid());

drop policy if exists "admins read reports" on public.forum_reports;
create policy "admins read reports" on public.forum_reports
  for select to authenticated using (public.is_admin());

-- ---------------------------------------------------------------------------
-- Rate limiting (server-side; the anon key is public so this cannot be bypassed
-- from the client). Tune the thresholds to taste.
-- ---------------------------------------------------------------------------
create or replace function public.enforce_post_rate_limit()
returns trigger language plpgsql security definer set search_path = public as $$
declare recent int;
begin
  select count(*) into recent from public.forum_posts
    where author_id = new.author_id and created_at > now() - interval '1 minute';
  if recent >= 8 then
    raise exception 'Rate limit: too many posts in a short time — slow down.';
  end if;
  return new;
end;
$$;
drop trigger if exists forum_posts_rate_limit on public.forum_posts;
create trigger forum_posts_rate_limit before insert on public.forum_posts
  for each row execute function public.enforce_post_rate_limit();

create or replace function public.enforce_thread_rate_limit()
returns trigger language plpgsql security definer set search_path = public as $$
declare recent int;
begin
  select count(*) into recent from public.forum_threads
    where author_id = new.author_id and created_at > now() - interval '5 minutes';
  if recent >= 3 then
    raise exception 'Rate limit: too many new threads — slow down.';
  end if;
  return new;
end;
$$;
drop trigger if exists forum_threads_rate_limit on public.forum_threads;
create trigger forum_threads_rate_limit before insert on public.forum_threads
  for each row execute function public.enforce_thread_rate_limit();

-- ---------------------------------------------------------------------------
-- Realtime. Add the forum tables to Supabase's realtime publication so the
-- client's live-update subscriptions receive INSERT/UPDATE events. Idempotent
-- (skips tables already in the publication). Reads still go through RLS, so
-- only world-readable rows are broadcast.
-- ---------------------------------------------------------------------------
do $$
begin
  if not exists (select 1 from pg_publication_tables
                 where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'forum_posts') then
    alter publication supabase_realtime add table public.forum_posts;
  end if;
  if not exists (select 1 from pg_publication_tables
                 where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'forum_threads') then
    alter publication supabase_realtime add table public.forum_threads;
  end if;
end $$;

-- --- END schema-forum-moderation.sql ---

-- ===========================================================================
-- BEGIN schema-profiles.sql
-- ===========================================================================

-- GopherTrunk — Supabase schema (Phase 4: richer profiles + avatar uploads)
--
-- Apply AFTER schema.sql (and, if you run the forum, after schema-forum.sql /
-- schema-forum-moderation.sql — order between this file and the forum files does
-- not matter, they touch different objects). SQL Editor -> paste -> Run, or
-- `supabase db push`. Idempotent: re-running is safe.
--
-- Everything here is ADDITIVE and the site FEATURE-DETECTS it: /profile/, /u/,
-- and the forum all keep working before this file is applied — the new fields
-- simply don't appear yet. Same security model as the earlier phases: the browser
-- holds only the public anon key, so every object is guarded by Row Level
-- Security, never by key secrecy.
--
-- Two things this file does:
--   1. Adds optional profile columns (bio, website, ham radio call sign, and an
--      optional country / region / city) with light validation.
--   2. Adds Row Level Security policies for a public `avatars` Storage bucket so a
--      signed-in user can upload/replace only their OWN avatar. You must still
--      CREATE the bucket in the dashboard first (see section 2 below for the exact
--      bucket name and settings).

-- ---------------------------------------------------------------------------
-- 1. profiles — new optional columns.
--
-- All nullable, so existing rows and the handle_new_user() signup trigger keep
-- working unchanged. `avatar_url` and `created_at` already exist (from schema.sql)
-- and are reused for the uploaded avatar and the "member since" date — no new
-- column needed for those.
-- ---------------------------------------------------------------------------
alter table public.profiles add column if not exists bio      text;
alter table public.profiles add column if not exists website  text;
alter table public.profiles add column if not exists callsign text;   -- amateur radio call sign
alter table public.profiles add column if not exists country  text;   -- ISO-3166 alpha-2, e.g. 'US'
alter table public.profiles add column if not exists region   text;   -- state / province (free text)
alter table public.profiles add column if not exists city     text;   -- free text

-- Constraints. ADD CONSTRAINT has no IF NOT EXISTS, so each is guarded on
-- pg_constraint. The regexes are deliberately permissive supersets — real
-- validation also happens client-side; these stop obviously bad or oversized
-- values from reaching the table.
do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'profiles_bio_chk') then
    alter table public.profiles add constraint profiles_bio_chk
      check (bio is null or char_length(bio) <= 1000);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'profiles_website_chk') then
    alter table public.profiles add constraint profiles_website_chk
      check (website is null or website ~* '^https?://[^ ]{3,200}$');
  end if;
  if not exists (select 1 from pg_constraint where conname = 'profiles_callsign_chk') then
    -- 3–10 chars, A–Z / 0–9 / '/', e.g. W1AW or W1AW/4. The client uppercases
    -- before saving, so lowercase input is normalised rather than rejected.
    alter table public.profiles add constraint profiles_callsign_chk
      check (callsign is null or callsign ~ '^[A-Z0-9/]{3,10}$');
  end if;
  if not exists (select 1 from pg_constraint where conname = 'profiles_country_chk') then
    alter table public.profiles add constraint profiles_country_chk
      check (country is null or country ~ '^[A-Z]{2}$');
  end if;
  if not exists (select 1 from pg_constraint where conname = 'profiles_region_chk') then
    alter table public.profiles add constraint profiles_region_chk
      check (region is null or char_length(region) <= 80);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'profiles_city_chk') then
    alter table public.profiles add constraint profiles_city_chk
      check (city is null or char_length(city) <= 80);
  end if;
end $$;

-- NOTE on `username`: it is intentionally NOT constrained here. Existing values
-- are seeded from OAuth metadata (GitHub usernames allow hyphens), so a
-- retroactive CHECK could fail this migration. Username format is validated in
-- the client (^[a-zA-Z0-9_-]{3,30}$, lowercased) on top of the existing UNIQUE.
-- The existing profiles RLS policies (public select, insert/update own) already
-- cover every new column, so no policy change is needed.

-- ---------------------------------------------------------------------------
-- 2. Avatar uploads — Storage RLS.
--
-- PREREQUISITE (dashboard, one time): create a PUBLIC bucket named `avatars`
--   Storage -> New bucket -> name `avatars`, Public = on,
--   file size limit 2 MB, allowed MIME types: image/png, image/jpeg, image/webp.
-- This file only adds the row-level policies; it does not create the bucket.
--
-- Path convention: `avatars/<uid>/avatar` — one fixed object key per user,
-- overwritten with upsert. The first path segment must equal the caller's uid,
-- so a signed-in user can only write inside their own folder. Reads are public
-- (the bucket is public, and read is world-open below) so avatars show for
-- everyone, including signed-out visitors on public profiles.
-- ---------------------------------------------------------------------------
drop policy if exists "avatars public read" on storage.objects;
create policy "avatars public read" on storage.objects
  for select using (bucket_id = 'avatars');

drop policy if exists "avatars insert own" on storage.objects;
create policy "avatars insert own" on storage.objects
  for insert to authenticated with check (
    bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text
  );

drop policy if exists "avatars update own" on storage.objects;
create policy "avatars update own" on storage.objects
  for update to authenticated using (
    bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text
  );

drop policy if exists "avatars delete own" on storage.objects;
create policy "avatars delete own" on storage.objects
  for delete to authenticated using (
    bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text
  );

-- --- END schema-profiles.sql ---

-- ===========================================================================
-- BEGIN schema-moderation.sql
-- ===========================================================================

-- GopherTrunk — Supabase schema (Phase 5: content moderation — bans, report
-- workflow, and an audit log)
--
-- Apply AFTER schema-forum.sql and schema-forum-moderation.sql (this file builds
-- on app_admins / is_admin() and the forum tables). SQL Editor -> paste -> Run.
-- Idempotent: re-running is safe.
--
-- Everything is ADDITIVE and FEATURE-DETECTED by the client, so the forum and the
-- /moderation/ dashboard keep working before this file is applied. Same security
-- model as every phase: the browser holds only the public anon key; all writes
-- are guarded by Row Level Security.
--
-- This file adds three things:
--   1. User bans / suspensions, enforced server-side so a banned user cannot post
--      even though they still hold a valid session and anon key.
--   2. A report workflow: reports can target a THREAD as well as a post, and each
--      report carries a status (open / reviewing / resolved / dismissed).
--   3. A moderation audit log recording every admin action.

create extension if not exists pgcrypto;   -- gen_random_uuid()

-- ---------------------------------------------------------------------------
-- 1. Bans / suspensions.
--
-- expires_at IS NULL  -> permanent ban.
-- expires_at > now()  -> temporary suspension (auto-lifts when it passes).
-- Grant/lift bans from the /moderation/ dashboard (admins), or directly via SQL:
--   insert into public.user_bans (user_id, reason) values ('<uuid>', 'spam');
--   delete from public.user_bans where user_id = '<uuid>';   -- unban
-- ---------------------------------------------------------------------------
create table if not exists public.user_bans (
  user_id    uuid primary key references public.profiles(id) on delete cascade,
  banned_by  uuid references public.profiles(id) on delete set null,
  reason     text check (reason is null or char_length(reason) <= 500),
  created_at timestamptz not null default now(),
  expires_at timestamptz            -- null = permanent; future ts = suspension
);
alter table public.user_bans enable row level security;

-- A signed-in user may read only their OWN ban row (so the forum can show
-- "you're suspended until…"); admins may read every row.
drop policy if exists "read own ban" on public.user_bans;
create policy "read own ban" on public.user_bans
  for select to authenticated using (user_id = auth.uid() or public.is_admin());

-- Only admins write bans. RLS combines permissive policies with OR, and no other
-- write policy exists, so non-admins are denied insert/update/delete.
drop policy if exists "admins manage bans" on public.user_bans;
create policy "admins manage bans" on public.user_bans
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- is_banned() — true while the caller has an active (non-expired) ban. SECURITY
-- DEFINER so it can read user_bans past RLS; it only ever checks auth.uid().
create or replace function public.is_banned()
returns boolean language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from public.user_bans
    where user_id = auth.uid()
      and (expires_at is null or expires_at > now())
  );
$$;
grant execute on function public.is_banned() to authenticated, anon;

-- Enforcement. The insert-own policies in schema-forum.sql are PERMISSIVE, which
-- OR together — so a new permissive policy could never *subtract* the right to
-- post. RESTRICTIVE policies AND with everything else, which is exactly what we
-- want: "you may post (existing rule) AND you are not banned". This keeps
-- schema-forum.sql untouched.
drop policy if exists "posts blocked while banned" on public.forum_posts;
create policy "posts blocked while banned" on public.forum_posts
  as restrictive for insert to authenticated with check (not public.is_banned());

-- Also block edits, so a banned user can't rewrite an existing post to route
-- around the insert block.
drop policy if exists "post edits blocked while banned" on public.forum_posts;
create policy "post edits blocked while banned" on public.forum_posts
  as restrictive for update to authenticated with check (not public.is_banned());

drop policy if exists "threads blocked while banned" on public.forum_threads;
create policy "threads blocked while banned" on public.forum_threads
  as restrictive for insert to authenticated with check (not public.is_banned());

-- ---------------------------------------------------------------------------
-- 2. Report workflow — extend forum_reports (from schema-forum-moderation.sql).
--
-- Adds thread reports (thread_id) and a status/resolution lifecycle. Additive:
-- existing post-only reports keep their post_id and default to status 'open'.
-- ---------------------------------------------------------------------------
alter table public.forum_reports add column if not exists thread_id   uuid references public.forum_threads(id) on delete cascade;
alter table public.forum_reports add column if not exists status      text not null default 'open';
alter table public.forum_reports add column if not exists resolved_by uuid references public.profiles(id) on delete set null;
alter table public.forum_reports add column if not exists resolved_at timestamptz;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'forum_reports_status_chk') then
    alter table public.forum_reports add constraint forum_reports_status_chk
      check (status in ('open', 'reviewing', 'resolved', 'dismissed'));
  end if;
  -- Exactly one target: a report is about a post OR a thread, never both/neither.
  -- Added NOT VALID so it applies to new/updated rows without re-checking any
  -- legacy rows (all of which already have a post_id, so they'd pass anyway).
  if not exists (select 1 from pg_constraint where conname = 'forum_reports_target_chk') then
    alter table public.forum_reports add constraint forum_reports_target_chk
      check ((post_id is not null) <> (thread_id is not null)) not valid;
  end if;
end $$;

create index if not exists forum_reports_status_idx on public.forum_reports (status, created_at desc);

-- Admins can update a report (change status, stamp resolved_by/at). The
-- insert-as-self and admins-read policies from schema-forum-moderation.sql still
-- apply.
drop policy if exists "admins update reports" on public.forum_reports;
create policy "admins update reports" on public.forum_reports
  for update to authenticated using (public.is_admin()) with check (public.is_admin());

-- ---------------------------------------------------------------------------
-- 3. Moderation audit log — one row per admin action, written by the dashboard.
-- Admin-only readable; admins insert rows stamped as themselves.
-- ---------------------------------------------------------------------------
create table if not exists public.moderation_actions (
  id          uuid primary key default gen_random_uuid(),
  actor_id    uuid not null references public.profiles(id) on delete set null,
  action      text not null,   -- 'lock_thread','unlock_thread','remove_post','ban_user','suspend_user','unban_user','resolve_report','dismiss_report'
  target_type text not null,   -- 'thread','post','user','report'
  target_id   uuid,
  detail      text check (detail is null or char_length(detail) <= 1000),
  created_at  timestamptz not null default now()
);
alter table public.moderation_actions enable row level security;
create index if not exists moderation_actions_created_idx on public.moderation_actions (created_at desc);

drop policy if exists "admins read audit" on public.moderation_actions;
create policy "admins read audit" on public.moderation_actions
  for select to authenticated using (public.is_admin());

drop policy if exists "admins write audit" on public.moderation_actions;
create policy "admins write audit" on public.moderation_actions
  for insert to authenticated with check (public.is_admin() and actor_id = auth.uid());

-- ---------------------------------------------------------------------------
-- 4. Realtime (optional) — let the moderation queue live-update. Idempotent:
-- skips tables already in the publication. Reads still pass through RLS, so only
-- admins receive these rows.
-- ---------------------------------------------------------------------------
do $$
begin
  if not exists (select 1 from pg_publication_tables
                 where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'forum_reports') then
    alter publication supabase_realtime add table public.forum_reports;
  end if;
  if not exists (select 1 from pg_publication_tables
                 where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'user_bans') then
    alter publication supabase_realtime add table public.user_bans;
  end if;
end $$;

-- --- END schema-moderation.sql ---
