// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: audio.proto

package apiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AudioFrame is one chunk of decoded PCM (or raw vocoder bytes) for an
// active call. Streamed from the daemon to subscribers.
type AudioFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Server-stamped time the frame was emitted (RFC 3339 UTC).
	Timestamp string `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// The call this frame belongs to. Source ID + group ID + start time
	// disambiguate concurrent calls on different Voice devices.
	Grant        *Grant `protobuf:"bytes,2,opt,name=grant,proto3" json:"grant,omitempty"`
	DeviceSerial string `protobuf:"bytes,3,opt,name=device_serial,json=deviceSerial,proto3" json:"device_serial,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*AudioFrame_Pcm
	//	*AudioFrame_Raw
	Body          isAudioFrame_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioFrame) Reset() {
	*x = AudioFrame{}
	mi := &file_audio_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioFrame) ProtoMessage() {}

func (x *AudioFrame) ProtoReflect() protoreflect.Message {
	mi := &file_audio_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioFrame.ProtoReflect.Descriptor instead.
func (*AudioFrame) Descriptor() ([]byte, []int) {
	return file_audio_proto_rawDescGZIP(), []int{0}
}

func (x *AudioFrame) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *AudioFrame) GetGrant() *Grant {
	if x != nil {
		return x.Grant
	}
	return nil
}

func (x *AudioFrame) GetDeviceSerial() string {
	if x != nil {
		return x.DeviceSerial
	}
	return ""
}

func (x *AudioFrame) GetBody() isAudioFrame_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *AudioFrame) GetPcm() *PCMSamples {
	if x != nil {
		if x, ok := x.Body.(*AudioFrame_Pcm); ok {
			return x.Pcm
		}
	}
	return nil
}

func (x *AudioFrame) GetRaw() *RawVocoderFrame {
	if x != nil {
		if x, ok := x.Body.(*AudioFrame_Raw); ok {
			return x.Raw
		}
	}
	return nil
}

type isAudioFrame_Body interface {
	isAudioFrame_Body()
}

type AudioFrame_Pcm struct {
	Pcm *PCMSamples `protobuf:"bytes,10,opt,name=pcm,proto3,oneof"` // decoded 16-bit mono PCM
}

type AudioFrame_Raw struct {
	Raw *RawVocoderFrame `protobuf:"bytes,11,opt,name=raw,proto3,oneof"` // un-decoded vocoder bytes (IMBE / AMBE+2)
}

func (*AudioFrame_Pcm) isAudioFrame_Body() {}

func (*AudioFrame_Raw) isAudioFrame_Body() {}

type PCMSamples struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	SampleRate uint32                 `protobuf:"varint,1,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"` // typically 8000
	// Little-endian 16-bit signed samples.
	Samples       []byte `protobuf:"bytes,2,opt,name=samples,proto3" json:"samples,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PCMSamples) Reset() {
	*x = PCMSamples{}
	mi := &file_audio_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PCMSamples) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PCMSamples) ProtoMessage() {}

func (x *PCMSamples) ProtoReflect() protoreflect.Message {
	mi := &file_audio_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PCMSamples.ProtoReflect.Descriptor instead.
func (*PCMSamples) Descriptor() ([]byte, []int) {
	return file_audio_proto_rawDescGZIP(), []int{1}
}

func (x *PCMSamples) GetSampleRate() uint32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

func (x *PCMSamples) GetSamples() []byte {
	if x != nil {
		return x.Samples
	}
	return nil
}

type RawVocoderFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Vocoder name as registered in the voice/Registry ("imbe", "ambe",
	// ...). "" means unknown / passthrough.
	Vocoder       string `protobuf:"bytes,1,opt,name=vocoder,proto3" json:"vocoder,omitempty"`
	Frame         []byte `protobuf:"bytes,2,opt,name=frame,proto3" json:"frame,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawVocoderFrame) Reset() {
	*x = RawVocoderFrame{}
	mi := &file_audio_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawVocoderFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawVocoderFrame) ProtoMessage() {}

func (x *RawVocoderFrame) ProtoReflect() protoreflect.Message {
	mi := &file_audio_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawVocoderFrame.ProtoReflect.Descriptor instead.
func (*RawVocoderFrame) Descriptor() ([]byte, []int) {
	return file_audio_proto_rawDescGZIP(), []int{2}
}

func (x *RawVocoderFrame) GetVocoder() string {
	if x != nil {
		return x.Vocoder
	}
	return ""
}

func (x *RawVocoderFrame) GetFrame() []byte {
	if x != nil {
		return x.Frame
	}
	return nil
}

type StreamAudioRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional filter: only emit frames for these device serials. Empty
	// matches all.
	DeviceSerials []string `protobuf:"bytes,1,rep,name=device_serials,json=deviceSerials,proto3" json:"device_serials,omitempty"`
	// Optional filter: only emit frames for these talkgroup IDs.
	TalkgroupIds []uint32 `protobuf:"varint,2,rep,packed,name=talkgroup_ids,json=talkgroupIds,proto3" json:"talkgroup_ids,omitempty"`
	// If true, also stream raw vocoder bytes (defaults false; PCM only).
	IncludeRaw    bool `protobuf:"varint,3,opt,name=include_raw,json=includeRaw,proto3" json:"include_raw,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamAudioRequest) Reset() {
	*x = StreamAudioRequest{}
	mi := &file_audio_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamAudioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamAudioRequest) ProtoMessage() {}

func (x *StreamAudioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_audio_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamAudioRequest.ProtoReflect.Descriptor instead.
func (*StreamAudioRequest) Descriptor() ([]byte, []int) {
	return file_audio_proto_rawDescGZIP(), []int{3}
}

func (x *StreamAudioRequest) GetDeviceSerials() []string {
	if x != nil {
		return x.DeviceSerials
	}
	return nil
}

func (x *StreamAudioRequest) GetTalkgroupIds() []uint32 {
	if x != nil {
		return x.TalkgroupIds
	}
	return nil
}

func (x *StreamAudioRequest) GetIncludeRaw() bool {
	if x != nil {
		return x.IncludeRaw
	}
	return false
}

var File_audio_proto protoreflect.FileDescriptor

const file_audio_proto_rawDesc = "" +
	"\n" +
	"\vaudio.proto\x12\x0egophertrunk.v1\x1a\fevents.proto\"\xe9\x01\n" +
	"\n" +
	"AudioFrame\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\tR\ttimestamp\x12+\n" +
	"\x05grant\x18\x02 \x01(\v2\x15.gophertrunk.v1.GrantR\x05grant\x12#\n" +
	"\rdevice_serial\x18\x03 \x01(\tR\fdeviceSerial\x12.\n" +
	"\x03pcm\x18\n" +
	" \x01(\v2\x1a.gophertrunk.v1.PCMSamplesH\x00R\x03pcm\x123\n" +
	"\x03raw\x18\v \x01(\v2\x1f.gophertrunk.v1.RawVocoderFrameH\x00R\x03rawB\x06\n" +
	"\x04body\"G\n" +
	"\n" +
	"PCMSamples\x12\x1f\n" +
	"\vsample_rate\x18\x01 \x01(\rR\n" +
	"sampleRate\x12\x18\n" +
	"\asamples\x18\x02 \x01(\fR\asamples\"A\n" +
	"\x0fRawVocoderFrame\x12\x18\n" +
	"\avocoder\x18\x01 \x01(\tR\avocoder\x12\x14\n" +
	"\x05frame\x18\x02 \x01(\fR\x05frame\"\x81\x01\n" +
	"\x12StreamAudioRequest\x12%\n" +
	"\x0edevice_serials\x18\x01 \x03(\tR\rdeviceSerials\x12#\n" +
	"\rtalkgroup_ids\x18\x02 \x03(\rR\ftalkgroupIds\x12\x1f\n" +
	"\vinclude_raw\x18\x03 \x01(\bR\n" +
	"includeRaw2_\n" +
	"\fAudioService\x12O\n" +
	"\vStreamAudio\x12\".gophertrunk.v1.StreamAudioRequest\x1a\x1a.gophertrunk.v1.AudioFrame0\x01B>Z<github.com/MattCheramie/GopherTrunk/internal/api/pb/v1;apiv1b\x06proto3"

var (
	file_audio_proto_rawDescOnce sync.Once
	file_audio_proto_rawDescData []byte
)

func file_audio_proto_rawDescGZIP() []byte {
	file_audio_proto_rawDescOnce.Do(func() {
		file_audio_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_audio_proto_rawDesc), len(file_audio_proto_rawDesc)))
	})
	return file_audio_proto_rawDescData
}

var file_audio_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_audio_proto_goTypes = []any{
	(*AudioFrame)(nil),         // 0: gophertrunk.v1.AudioFrame
	(*PCMSamples)(nil),         // 1: gophertrunk.v1.PCMSamples
	(*RawVocoderFrame)(nil),    // 2: gophertrunk.v1.RawVocoderFrame
	(*StreamAudioRequest)(nil), // 3: gophertrunk.v1.StreamAudioRequest
	(*Grant)(nil),              // 4: gophertrunk.v1.Grant
}
var file_audio_proto_depIdxs = []int32{
	4, // 0: gophertrunk.v1.AudioFrame.grant:type_name -> gophertrunk.v1.Grant
	1, // 1: gophertrunk.v1.AudioFrame.pcm:type_name -> gophertrunk.v1.PCMSamples
	2, // 2: gophertrunk.v1.AudioFrame.raw:type_name -> gophertrunk.v1.RawVocoderFrame
	3, // 3: gophertrunk.v1.AudioService.StreamAudio:input_type -> gophertrunk.v1.StreamAudioRequest
	0, // 4: gophertrunk.v1.AudioService.StreamAudio:output_type -> gophertrunk.v1.AudioFrame
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_audio_proto_init() }
func file_audio_proto_init() {
	if File_audio_proto != nil {
		return
	}
	file_events_proto_init()
	file_audio_proto_msgTypes[0].OneofWrappers = []any{
		(*AudioFrame_Pcm)(nil),
		(*AudioFrame_Raw)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_audio_proto_rawDesc), len(file_audio_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_audio_proto_goTypes,
		DependencyIndexes: file_audio_proto_depIdxs,
		MessageInfos:      file_audio_proto_msgTypes,
	}.Build()
	File_audio_proto = out.File
	file_audio_proto_goTypes = nil
	file_audio_proto_depIdxs = nil
}
