// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: system.proto

package apiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// System mirrors trunking.System.
type System struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Protocol        string                 `protobuf:"bytes,2,opt,name=protocol,proto3" json:"protocol,omitempty"`                                              // "p25" / "dmr" / "nxdn"
	ControlChannels []uint32               `protobuf:"varint,3,rep,packed,name=control_channels,json=controlChannels,proto3" json:"control_channels,omitempty"` // candidate frequencies in Hz
	Wacn            uint32                 `protobuf:"varint,4,opt,name=wacn,proto3" json:"wacn,omitempty"`                                                     // 20-bit (P25)
	SystemId        uint32                 `protobuf:"varint,5,opt,name=system_id,json=systemId,proto3" json:"system_id,omitempty"`                             // 12-bit
	Rfss            uint32                 `protobuf:"varint,6,opt,name=rfss,proto3" json:"rfss,omitempty"`
	Site            uint32                 `protobuf:"varint,7,opt,name=site,proto3" json:"site,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *System) Reset() {
	*x = System{}
	mi := &file_system_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *System) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*System) ProtoMessage() {}

func (x *System) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use System.ProtoReflect.Descriptor instead.
func (*System) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{0}
}

func (x *System) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *System) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *System) GetControlChannels() []uint32 {
	if x != nil {
		return x.ControlChannels
	}
	return nil
}

func (x *System) GetWacn() uint32 {
	if x != nil {
		return x.Wacn
	}
	return 0
}

func (x *System) GetSystemId() uint32 {
	if x != nil {
		return x.SystemId
	}
	return 0
}

func (x *System) GetRfss() uint32 {
	if x != nil {
		return x.Rfss
	}
	return 0
}

func (x *System) GetSite() uint32 {
	if x != nil {
		return x.Site
	}
	return 0
}

type ListSystemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSystemsRequest) Reset() {
	*x = ListSystemsRequest{}
	mi := &file_system_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSystemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSystemsRequest) ProtoMessage() {}

func (x *ListSystemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSystemsRequest.ProtoReflect.Descriptor instead.
func (*ListSystemsRequest) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{1}
}

type ListSystemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Systems       []*System              `protobuf:"bytes,1,rep,name=systems,proto3" json:"systems,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSystemsResponse) Reset() {
	*x = ListSystemsResponse{}
	mi := &file_system_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSystemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSystemsResponse) ProtoMessage() {}

func (x *ListSystemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSystemsResponse.ProtoReflect.Descriptor instead.
func (*ListSystemsResponse) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{2}
}

func (x *ListSystemsResponse) GetSystems() []*System {
	if x != nil {
		return x.Systems
	}
	return nil
}

type GetSystemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSystemRequest) Reset() {
	*x = GetSystemRequest{}
	mi := &file_system_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSystemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSystemRequest) ProtoMessage() {}

func (x *GetSystemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSystemRequest.ProtoReflect.Descriptor instead.
func (*GetSystemRequest) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{3}
}

func (x *GetSystemRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetSystemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	System        *System                `protobuf:"bytes,1,opt,name=system,proto3" json:"system,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSystemResponse) Reset() {
	*x = GetSystemResponse{}
	mi := &file_system_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSystemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSystemResponse) ProtoMessage() {}

func (x *GetSystemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSystemResponse.ProtoReflect.Descriptor instead.
func (*GetSystemResponse) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{4}
}

func (x *GetSystemResponse) GetSystem() *System {
	if x != nil {
		return x.System
	}
	return nil
}

var File_system_proto protoreflect.FileDescriptor

const file_system_proto_rawDesc = "" +
	"\n" +
	"\fsystem.proto\x12\x0egophertrunk.v1\"\xbc\x01\n" +
	"\x06System\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bprotocol\x18\x02 \x01(\tR\bprotocol\x12)\n" +
	"\x10control_channels\x18\x03 \x03(\rR\x0fcontrolChannels\x12\x12\n" +
	"\x04wacn\x18\x04 \x01(\rR\x04wacn\x12\x1b\n" +
	"\tsystem_id\x18\x05 \x01(\rR\bsystemId\x12\x12\n" +
	"\x04rfss\x18\x06 \x01(\rR\x04rfss\x12\x12\n" +
	"\x04site\x18\a \x01(\rR\x04site\"\x14\n" +
	"\x12ListSystemsRequest\"G\n" +
	"\x13ListSystemsResponse\x120\n" +
	"\asystems\x18\x01 \x03(\v2\x16.gophertrunk.v1.SystemR\asystems\"&\n" +
	"\x10GetSystemRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"C\n" +
	"\x11GetSystemResponse\x12.\n" +
	"\x06system\x18\x01 \x01(\v2\x16.gophertrunk.v1.SystemR\x06system2\xb9\x01\n" +
	"\rSystemService\x12V\n" +
	"\vListSystems\x12\".gophertrunk.v1.ListSystemsRequest\x1a#.gophertrunk.v1.ListSystemsResponse\x12P\n" +
	"\tGetSystem\x12 .gophertrunk.v1.GetSystemRequest\x1a!.gophertrunk.v1.GetSystemResponseB>Z<github.com/MattCheramie/GopherTrunk/internal/api/pb/v1;apiv1b\x06proto3"

var (
	file_system_proto_rawDescOnce sync.Once
	file_system_proto_rawDescData []byte
)

func file_system_proto_rawDescGZIP() []byte {
	file_system_proto_rawDescOnce.Do(func() {
		file_system_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_system_proto_rawDesc), len(file_system_proto_rawDesc)))
	})
	return file_system_proto_rawDescData
}

var file_system_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_system_proto_goTypes = []any{
	(*System)(nil),              // 0: gophertrunk.v1.System
	(*ListSystemsRequest)(nil),  // 1: gophertrunk.v1.ListSystemsRequest
	(*ListSystemsResponse)(nil), // 2: gophertrunk.v1.ListSystemsResponse
	(*GetSystemRequest)(nil),    // 3: gophertrunk.v1.GetSystemRequest
	(*GetSystemResponse)(nil),   // 4: gophertrunk.v1.GetSystemResponse
}
var file_system_proto_depIdxs = []int32{
	0, // 0: gophertrunk.v1.ListSystemsResponse.systems:type_name -> gophertrunk.v1.System
	0, // 1: gophertrunk.v1.GetSystemResponse.system:type_name -> gophertrunk.v1.System
	1, // 2: gophertrunk.v1.SystemService.ListSystems:input_type -> gophertrunk.v1.ListSystemsRequest
	3, // 3: gophertrunk.v1.SystemService.GetSystem:input_type -> gophertrunk.v1.GetSystemRequest
	2, // 4: gophertrunk.v1.SystemService.ListSystems:output_type -> gophertrunk.v1.ListSystemsResponse
	4, // 5: gophertrunk.v1.SystemService.GetSystem:output_type -> gophertrunk.v1.GetSystemResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_system_proto_init() }
func file_system_proto_init() {
	if File_system_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_system_proto_rawDesc), len(file_system_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_system_proto_goTypes,
		DependencyIndexes: file_system_proto_depIdxs,
		MessageInfos:      file_system_proto_msgTypes,
	}.Build()
	File_system_proto = out.File
	file_system_proto_goTypes = nil
	file_system_proto_depIdxs = nil
}
