// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: talkgroup.proto

package apiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListTalkgroupsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional system filter; empty = all systems.
	System        string `protobuf:"bytes,1,opt,name=system,proto3" json:"system,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTalkgroupsRequest) Reset() {
	*x = ListTalkgroupsRequest{}
	mi := &file_talkgroup_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTalkgroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTalkgroupsRequest) ProtoMessage() {}

func (x *ListTalkgroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_talkgroup_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTalkgroupsRequest.ProtoReflect.Descriptor instead.
func (*ListTalkgroupsRequest) Descriptor() ([]byte, []int) {
	return file_talkgroup_proto_rawDescGZIP(), []int{0}
}

func (x *ListTalkgroupsRequest) GetSystem() string {
	if x != nil {
		return x.System
	}
	return ""
}

type ListTalkgroupsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Talkgroups    []*TalkGroup           `protobuf:"bytes,1,rep,name=talkgroups,proto3" json:"talkgroups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTalkgroupsResponse) Reset() {
	*x = ListTalkgroupsResponse{}
	mi := &file_talkgroup_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTalkgroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTalkgroupsResponse) ProtoMessage() {}

func (x *ListTalkgroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_talkgroup_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTalkgroupsResponse.ProtoReflect.Descriptor instead.
func (*ListTalkgroupsResponse) Descriptor() ([]byte, []int) {
	return file_talkgroup_proto_rawDescGZIP(), []int{1}
}

func (x *ListTalkgroupsResponse) GetTalkgroups() []*TalkGroup {
	if x != nil {
		return x.Talkgroups
	}
	return nil
}

type GetTalkgroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTalkgroupRequest) Reset() {
	*x = GetTalkgroupRequest{}
	mi := &file_talkgroup_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTalkgroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTalkgroupRequest) ProtoMessage() {}

func (x *GetTalkgroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_talkgroup_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTalkgroupRequest.ProtoReflect.Descriptor instead.
func (*GetTalkgroupRequest) Descriptor() ([]byte, []int) {
	return file_talkgroup_proto_rawDescGZIP(), []int{2}
}

func (x *GetTalkgroupRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetTalkgroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Talkgroup     *TalkGroup             `protobuf:"bytes,1,opt,name=talkgroup,proto3" json:"talkgroup,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTalkgroupResponse) Reset() {
	*x = GetTalkgroupResponse{}
	mi := &file_talkgroup_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTalkgroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTalkgroupResponse) ProtoMessage() {}

func (x *GetTalkgroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_talkgroup_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTalkgroupResponse.ProtoReflect.Descriptor instead.
func (*GetTalkgroupResponse) Descriptor() ([]byte, []int) {
	return file_talkgroup_proto_rawDescGZIP(), []int{3}
}

func (x *GetTalkgroupResponse) GetTalkgroup() *TalkGroup {
	if x != nil {
		return x.Talkgroup
	}
	return nil
}

type ListActiveCallsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActiveCallsRequest) Reset() {
	*x = ListActiveCallsRequest{}
	mi := &file_talkgroup_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActiveCallsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActiveCallsRequest) ProtoMessage() {}

func (x *ListActiveCallsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_talkgroup_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActiveCallsRequest.ProtoReflect.Descriptor instead.
func (*ListActiveCallsRequest) Descriptor() ([]byte, []int) {
	return file_talkgroup_proto_rawDescGZIP(), []int{4}
}

type ActiveCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Grant         *Grant                 `protobuf:"bytes,1,opt,name=grant,proto3" json:"grant,omitempty"`
	Talkgroup     *TalkGroup             `protobuf:"bytes,2,opt,name=talkgroup,proto3" json:"talkgroup,omitempty"`
	DeviceSerial  string                 `protobuf:"bytes,3,opt,name=device_serial,json=deviceSerial,proto3" json:"device_serial,omitempty"`
	StartedAt     string                 `protobuf:"bytes,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	LastHeardAt   string                 `protobuf:"bytes,5,opt,name=last_heard_at,json=lastHeardAt,proto3" json:"last_heard_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActiveCall) Reset() {
	*x = ActiveCall{}
	mi := &file_talkgroup_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActiveCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActiveCall) ProtoMessage() {}

func (x *ActiveCall) ProtoReflect() protoreflect.Message {
	mi := &file_talkgroup_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActiveCall.ProtoReflect.Descriptor instead.
func (*ActiveCall) Descriptor() ([]byte, []int) {
	return file_talkgroup_proto_rawDescGZIP(), []int{5}
}

func (x *ActiveCall) GetGrant() *Grant {
	if x != nil {
		return x.Grant
	}
	return nil
}

func (x *ActiveCall) GetTalkgroup() *TalkGroup {
	if x != nil {
		return x.Talkgroup
	}
	return nil
}

func (x *ActiveCall) GetDeviceSerial() string {
	if x != nil {
		return x.DeviceSerial
	}
	return ""
}

func (x *ActiveCall) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *ActiveCall) GetLastHeardAt() string {
	if x != nil {
		return x.LastHeardAt
	}
	return ""
}

type ListActiveCallsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Calls         []*ActiveCall          `protobuf:"bytes,1,rep,name=calls,proto3" json:"calls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActiveCallsResponse) Reset() {
	*x = ListActiveCallsResponse{}
	mi := &file_talkgroup_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActiveCallsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActiveCallsResponse) ProtoMessage() {}

func (x *ListActiveCallsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_talkgroup_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActiveCallsResponse.ProtoReflect.Descriptor instead.
func (*ListActiveCallsResponse) Descriptor() ([]byte, []int) {
	return file_talkgroup_proto_rawDescGZIP(), []int{6}
}

func (x *ListActiveCallsResponse) GetCalls() []*ActiveCall {
	if x != nil {
		return x.Calls
	}
	return nil
}

var File_talkgroup_proto protoreflect.FileDescriptor

const file_talkgroup_proto_rawDesc = "" +
	"\n" +
	"\x0ftalkgroup.proto\x12\x0egophertrunk.v1\x1a\fevents.proto\"/\n" +
	"\x15ListTalkgroupsRequest\x12\x16\n" +
	"\x06system\x18\x01 \x01(\tR\x06system\"S\n" +
	"\x16ListTalkgroupsResponse\x129\n" +
	"\n" +
	"talkgroups\x18\x01 \x03(\v2\x19.gophertrunk.v1.TalkGroupR\n" +
	"talkgroups\"%\n" +
	"\x13GetTalkgroupRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"O\n" +
	"\x14GetTalkgroupResponse\x127\n" +
	"\ttalkgroup\x18\x01 \x01(\v2\x19.gophertrunk.v1.TalkGroupR\ttalkgroup\"\x18\n" +
	"\x16ListActiveCallsRequest\"\xda\x01\n" +
	"\n" +
	"ActiveCall\x12+\n" +
	"\x05grant\x18\x01 \x01(\v2\x15.gophertrunk.v1.GrantR\x05grant\x127\n" +
	"\ttalkgroup\x18\x02 \x01(\v2\x19.gophertrunk.v1.TalkGroupR\ttalkgroup\x12#\n" +
	"\rdevice_serial\x18\x03 \x01(\tR\fdeviceSerial\x12\x1d\n" +
	"\n" +
	"started_at\x18\x04 \x01(\tR\tstartedAt\x12\"\n" +
	"\rlast_heard_at\x18\x05 \x01(\tR\vlastHeardAt\"K\n" +
	"\x17ListActiveCallsResponse\x120\n" +
	"\x05calls\x18\x01 \x03(\v2\x1a.gophertrunk.v1.ActiveCallR\x05calls2\xb2\x02\n" +
	"\x10TalkgroupService\x12_\n" +
	"\x0eListTalkgroups\x12%.gophertrunk.v1.ListTalkgroupsRequest\x1a&.gophertrunk.v1.ListTalkgroupsResponse\x12Y\n" +
	"\fGetTalkgroup\x12#.gophertrunk.v1.GetTalkgroupRequest\x1a$.gophertrunk.v1.GetTalkgroupResponse\x12b\n" +
	"\x0fListActiveCalls\x12&.gophertrunk.v1.ListActiveCallsRequest\x1a'.gophertrunk.v1.ListActiveCallsResponseB>Z<github.com/MattCheramie/GopherTrunk/internal/api/pb/v1;apiv1b\x06proto3"

var (
	file_talkgroup_proto_rawDescOnce sync.Once
	file_talkgroup_proto_rawDescData []byte
)

func file_talkgroup_proto_rawDescGZIP() []byte {
	file_talkgroup_proto_rawDescOnce.Do(func() {
		file_talkgroup_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_talkgroup_proto_rawDesc), len(file_talkgroup_proto_rawDesc)))
	})
	return file_talkgroup_proto_rawDescData
}

var file_talkgroup_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_talkgroup_proto_goTypes = []any{
	(*ListTalkgroupsRequest)(nil),   // 0: gophertrunk.v1.ListTalkgroupsRequest
	(*ListTalkgroupsResponse)(nil),  // 1: gophertrunk.v1.ListTalkgroupsResponse
	(*GetTalkgroupRequest)(nil),     // 2: gophertrunk.v1.GetTalkgroupRequest
	(*GetTalkgroupResponse)(nil),    // 3: gophertrunk.v1.GetTalkgroupResponse
	(*ListActiveCallsRequest)(nil),  // 4: gophertrunk.v1.ListActiveCallsRequest
	(*ActiveCall)(nil),              // 5: gophertrunk.v1.ActiveCall
	(*ListActiveCallsResponse)(nil), // 6: gophertrunk.v1.ListActiveCallsResponse
	(*TalkGroup)(nil),               // 7: gophertrunk.v1.TalkGroup
	(*Grant)(nil),                   // 8: gophertrunk.v1.Grant
}
var file_talkgroup_proto_depIdxs = []int32{
	7, // 0: gophertrunk.v1.ListTalkgroupsResponse.talkgroups:type_name -> gophertrunk.v1.TalkGroup
	7, // 1: gophertrunk.v1.GetTalkgroupResponse.talkgroup:type_name -> gophertrunk.v1.TalkGroup
	8, // 2: gophertrunk.v1.ActiveCall.grant:type_name -> gophertrunk.v1.Grant
	7, // 3: gophertrunk.v1.ActiveCall.talkgroup:type_name -> gophertrunk.v1.TalkGroup
	5, // 4: gophertrunk.v1.ListActiveCallsResponse.calls:type_name -> gophertrunk.v1.ActiveCall
	0, // 5: gophertrunk.v1.TalkgroupService.ListTalkgroups:input_type -> gophertrunk.v1.ListTalkgroupsRequest
	2, // 6: gophertrunk.v1.TalkgroupService.GetTalkgroup:input_type -> gophertrunk.v1.GetTalkgroupRequest
	4, // 7: gophertrunk.v1.TalkgroupService.ListActiveCalls:input_type -> gophertrunk.v1.ListActiveCallsRequest
	1, // 8: gophertrunk.v1.TalkgroupService.ListTalkgroups:output_type -> gophertrunk.v1.ListTalkgroupsResponse
	3, // 9: gophertrunk.v1.TalkgroupService.GetTalkgroup:output_type -> gophertrunk.v1.GetTalkgroupResponse
	6, // 10: gophertrunk.v1.TalkgroupService.ListActiveCalls:output_type -> gophertrunk.v1.ListActiveCallsResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_talkgroup_proto_init() }
func file_talkgroup_proto_init() {
	if File_talkgroup_proto != nil {
		return
	}
	file_events_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_talkgroup_proto_rawDesc), len(file_talkgroup_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_talkgroup_proto_goTypes,
		DependencyIndexes: file_talkgroup_proto_depIdxs,
		MessageInfos:      file_talkgroup_proto_msgTypes,
	}.Build()
	File_talkgroup_proto = out.File
	file_talkgroup_proto_goTypes = nil
	file_talkgroup_proto_depIdxs = nil
}
