// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: talkgroup.proto

package apiv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TalkgroupService_ListTalkgroups_FullMethodName  = "/gophertrunk.v1.TalkgroupService/ListTalkgroups"
	TalkgroupService_GetTalkgroup_FullMethodName    = "/gophertrunk.v1.TalkgroupService/GetTalkgroup"
	TalkgroupService_ListActiveCalls_FullMethodName = "/gophertrunk.v1.TalkgroupService/ListActiveCalls"
)

// TalkgroupServiceClient is the client API for TalkgroupService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TalkgroupServiceClient interface {
	ListTalkgroups(ctx context.Context, in *ListTalkgroupsRequest, opts ...grpc.CallOption) (*ListTalkgroupsResponse, error)
	GetTalkgroup(ctx context.Context, in *GetTalkgroupRequest, opts ...grpc.CallOption) (*GetTalkgroupResponse, error)
	ListActiveCalls(ctx context.Context, in *ListActiveCallsRequest, opts ...grpc.CallOption) (*ListActiveCallsResponse, error)
}

type talkgroupServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTalkgroupServiceClient(cc grpc.ClientConnInterface) TalkgroupServiceClient {
	return &talkgroupServiceClient{cc}
}

func (c *talkgroupServiceClient) ListTalkgroups(ctx context.Context, in *ListTalkgroupsRequest, opts ...grpc.CallOption) (*ListTalkgroupsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTalkgroupsResponse)
	err := c.cc.Invoke(ctx, TalkgroupService_ListTalkgroups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *talkgroupServiceClient) GetTalkgroup(ctx context.Context, in *GetTalkgroupRequest, opts ...grpc.CallOption) (*GetTalkgroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTalkgroupResponse)
	err := c.cc.Invoke(ctx, TalkgroupService_GetTalkgroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *talkgroupServiceClient) ListActiveCalls(ctx context.Context, in *ListActiveCallsRequest, opts ...grpc.CallOption) (*ListActiveCallsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListActiveCallsResponse)
	err := c.cc.Invoke(ctx, TalkgroupService_ListActiveCalls_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TalkgroupServiceServer is the server API for TalkgroupService service.
// All implementations must embed UnimplementedTalkgroupServiceServer
// for forward compatibility.
type TalkgroupServiceServer interface {
	ListTalkgroups(context.Context, *ListTalkgroupsRequest) (*ListTalkgroupsResponse, error)
	GetTalkgroup(context.Context, *GetTalkgroupRequest) (*GetTalkgroupResponse, error)
	ListActiveCalls(context.Context, *ListActiveCallsRequest) (*ListActiveCallsResponse, error)
	mustEmbedUnimplementedTalkgroupServiceServer()
}

// UnimplementedTalkgroupServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTalkgroupServiceServer struct{}

func (UnimplementedTalkgroupServiceServer) ListTalkgroups(context.Context, *ListTalkgroupsRequest) (*ListTalkgroupsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTalkgroups not implemented")
}
func (UnimplementedTalkgroupServiceServer) GetTalkgroup(context.Context, *GetTalkgroupRequest) (*GetTalkgroupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTalkgroup not implemented")
}
func (UnimplementedTalkgroupServiceServer) ListActiveCalls(context.Context, *ListActiveCallsRequest) (*ListActiveCallsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListActiveCalls not implemented")
}
func (UnimplementedTalkgroupServiceServer) mustEmbedUnimplementedTalkgroupServiceServer() {}
func (UnimplementedTalkgroupServiceServer) testEmbeddedByValue()                          {}

// UnsafeTalkgroupServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TalkgroupServiceServer will
// result in compilation errors.
type UnsafeTalkgroupServiceServer interface {
	mustEmbedUnimplementedTalkgroupServiceServer()
}

func RegisterTalkgroupServiceServer(s grpc.ServiceRegistrar, srv TalkgroupServiceServer) {
	// If the following call panics, it indicates UnimplementedTalkgroupServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TalkgroupService_ServiceDesc, srv)
}

func _TalkgroupService_ListTalkgroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTalkgroupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TalkgroupServiceServer).ListTalkgroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TalkgroupService_ListTalkgroups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TalkgroupServiceServer).ListTalkgroups(ctx, req.(*ListTalkgroupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TalkgroupService_GetTalkgroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTalkgroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TalkgroupServiceServer).GetTalkgroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TalkgroupService_GetTalkgroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TalkgroupServiceServer).GetTalkgroup(ctx, req.(*GetTalkgroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TalkgroupService_ListActiveCalls_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListActiveCallsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TalkgroupServiceServer).ListActiveCalls(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TalkgroupService_ListActiveCalls_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TalkgroupServiceServer).ListActiveCalls(ctx, req.(*ListActiveCallsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TalkgroupService_ServiceDesc is the grpc.ServiceDesc for TalkgroupService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TalkgroupService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gophertrunk.v1.TalkgroupService",
	HandlerType: (*TalkgroupServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListTalkgroups",
			Handler:    _TalkgroupService_ListTalkgroups_Handler,
		},
		{
			MethodName: "GetTalkgroup",
			Handler:    _TalkgroupService_GetTalkgroup_Handler,
		},
		{
			MethodName: "ListActiveCalls",
			Handler:    _TalkgroupService_ListActiveCalls_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "talkgroup.proto",
}
